
Gold              = 1.618                          # nothing to do with the group from the 80's
Width             = 12
Height            = Width/Gold
WidthPx           = 1024
HeightPx          = WidthPx/Gold

AssetsDir         = "assets"                       # subdirectory where intermediates files are stored
ScrapyLogFile     = "scrapy.log"                   # logs generated by scrapy
Filename          = "cities.csv"                   # the files generated by kayak_part1.ipynb. Ordered list of town
OneCityFile       = "one_city.json"                # contains the name of the current city
HotelsListFile    = "hotels_list.json"             # contains the hotels for one city
HotelsAttributes  = "hotels_attributes.json"       # contains the attributes of 20+ the hotels in the current town 
TripDataCSV       = "travel_data.csv"              # final csv file
TripDataSQLITE    = "travel_data.sqlite"
TripDataSQL       = "travel_data.sql"