# When running locally using docker
docker run -it\
 -p 4000:4000\
 -v "$(pwd):/home/app"\
 -e PORT=4000\
 -e MLFLOW_TRACKING_URI=REPLACE_WITH_YOUR_MLFLOW_TRACKING_URI
 -e AWS_ACCESS_KEY_ID=REPLACE_WITH_YOUR_AWS_ACCESS_KEY_ID\
 -e AWS_SECRET_ACCESS_KEY=REPLACE_WITH_YOUR_AWS_SECRET_ACCESS_KEY\
 -e BACKEND_STORE_URI=REPLACE_WITH_YOUR_BACKEND_STORE_URI\
 -e ARTIFACT_ROOT=REPLACE_WITH_YOUR_ARTIFACT_ROOT\
 jedha/sample-mlflow-server python train.py